// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dmzbxgoqncqiaowukbah.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRtemJ4Z29xbmNxaWFvd3VrYmFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzc4Nzk2ODgsImV4cCI6MjA1MzQ1NTY4OH0.NAYettxg55P61alDFTXXqOu_1bPHWxOeD1wMb2-TOLM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);